### ISSUE TITLE
listen on ipv6?

### ISSUE THREAD

**Issue by czane** [benzman81/homebridge-http-webhooks#92]
is there a way to get webhooks listening on ipv6? A netstat -an shows 51828 only bound to tcp and not tcp6. 

running the homebridge raspberry pi iso. All plugins were installed via the web interface

**Comment by benzman81** [comment]
@czane with the new version 0.0.62 you can set "webhook_listen_host" to "::". Using this the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise. Note: In most operating systems, listening to the unspecified IPv6 address (::) may cause the server to also listen on the unspecified IPv4 address (0.0.0.0).

**Comment by czane** [comment]
works perfectly! thank you!
